import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

<link rel="icon" href="/icon.png" />

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Quizard - A quiz app",
  description: "Generated by create next app",
   icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          {children}
        
      </body>
    </html>
  );
}
